title:  "Road From Formosa"
tagline: "a travel blog"
description:
author:
  name: "Angela 高 "

# Change to true for Disqus comments
disqus:
comments: false
disqus_shortname: 'fromformosa'

menu:

- {name: 'Blog', file: 'blog.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'instagram', link: 'https://instagram.com/nemomymy'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
